apiVersion: psmdb.percona.com/v1-11-0
kind: PerconaServerMongoDB
metadata:
  name: mongo
  namespace: resultsdb
spec:
  crVersion: 1.11.0
  image: percona/percona-server-mongodb:4.4.10-11
  allowUnsafeConfigurations: true
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-recommended
    schedule: "0 2 * * *"
  secrets:
    users: resultsdb
  replsets:
  - name: rs0
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 100Gi
