namespace: modeldb

resources:
- ns.yaml
- mysql-operator.yaml

secretGenerator:
- name: modeldb-passwords
  literals:
  - rootUser=root
  - rootHost=%
  files:
  - rootPassword=etc/.secrets/rootPassword

generatorOptions:
  disableNameSuffixHash: true
