$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: prefect-server-postgresql

---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: prefect-server-postgresql
---

$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: prefect-server-postgresql-headless

